2nd Push
Erstellung der Eingabefelder des Formulars zur Eingabe der Impfdaten für den Nachweis

jinja2.exceptions.TemplateSyntaxError kann nicht behoben werden.

Beschreibung:
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor'. The innermost block that needs to be closed is 'for'.